# Use official Tomcat 9 with Java 11
FROM tomcat:9.0-jdk11-openjdk

# Remove default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Add your WAR file as ROOT application
COPY Online_Electronic_Store.war /usr/local/tomcat/webapps/ROOT.war

# Expose port (optional, Render uses its own)
EXPOSE 8080

CMD ["catalina.sh", "run"]
